module Ascii where
import System.Console.ANSI

bold :: String -> IO()
bold x = do 
        setSGR [SetConsoleIntensity BoldIntensity]
        putStrLn (x)
        setSGR [Reset]

ascii :: Int -> IO()
ascii 0  = 
  putStrLn (("\n================================================== "
          ++ "\n|'.                    (|)                     .'|"
          ++ "\n|  '.                   |                    .'  |"
          ++ "\n|    '.                |O|                 .'    |"
          ++ "\n|      '. ____________/===\\_____________ .'      |"
          ++ "\n|        :            `\\\"/`  ______     :     .. |"
          ++ "\n|        :     mmmmmmm  V   |--%%--|    :   .'|| |"
          ++ "\n|        :     |  |  |      |-%%%%-|    :  |  || |"
          ++ "\n|        :     |--|--| @@@  |=_||_=|    :  I  || |"
          ++ "\n|        :     |__|__|@@@@@ |_\\__/_|    :  |  || |"
          ++ "\n|        :             \\|/   ____       :  |  || |"
          ++ "\n|        :;;       .'``(_)```\\__/````:  :  |  || |"
          ++ "\n|        :||___   :================:'|  :  | 0+| |"
          ++ "\n|        :||===)  | |              | |  :  |  || |"
          ++ "\n|        ://``\\\\__|_|______________|_|__:  I  || |"
          ++ "\n|      .'/'    \\' | '              | '   '.|  || |"
          ++ "\n|    .'           |                |       '. || |"
          ++ "\n|  .'                                        '|| |"
          ++ "\n|.'      from http://ascii.co.uk/art/room      '.|"
          ++ "\n==================================================  "))  
ascii 1  = 
 putStrLn (("     `!,"
       ++ "\n    -( )-"
       ++ "\n    /'|\\`                        /"
       ++ "\n      | \\ `                     //"
       ++ "\n                               ///"
       ++ "\n             ###              /[_]"
       ++ "\n            #####              []["
       ++ "\n          #{##{####       o~   [_]"
       ++ "\n         ###\\#}#}###      /`\\  []["
       ++ "\n          ###\\{/###      [ /%\\ [_]"
       ++ "\n           # }}{ #       [_|_\\_[]["
       ++ "\n       ###   }}{           [_][__]"
       ++ "\n      #\\#}#} }}{@  @       [___][]"
       ++ "\n      ##\\/## }}{|@@|/      [_][__]"
       ++ "\n,ejm,,,,}{,,,}{{||||_______[___][]"))

ascii 2  = 
 putStrLn ((" ____________________"
       ++ "\n/                    \\"
       ++ "\n!      CASTLE         \\"
       ++ "\n!                     /"
       ++ "\n\\____________________/"
       ++ "\n         !  !"
       ++ "\n         !  !"
       ++ "\n  _______⅃__L_________"
       ++ "\n /                    \\"
       ++ "\n/      Mountain /     !"
       ++ "\n\\      Canyon         !"
       ++ "\n \\____________________/"
       ++ "\n         !  !"
       ++ "\n         !  !"
       ++ "\n ________⅃__L________"
       ++ "\n/  /\\                \\"
       ++ "\n! /__\\   Forest      !"
       ++ "\n!  ||                !"
       ++ "\n\\____________________/"
       ++ "\n         !  !"
       ++ "\n         !  ! " 
       ++ "\n         !  !"
       ++ "\n         !  !"
       ++ "\n         !  !"
       ++ "\n         \\__/ " )) 
ascii 3  = 
 putStrLn (("____________________________  ______________#_____"
       ++ "\n                           /  \\           #####   "     
       ++ "\n                          /    \\         ##o####   "        
       ++ "\n                         /      \\       #####o###   "       
       ++ "\n                        /        \\     #o#\\#|#/###   "       
       ++ "\n                       /          \\     ###\\|/#o#     "      
       ++ "\n                      /            \\       }|{       "
       ++ "\n                     /              \\      }|{   "
       ++ "\n                    /                \\    "
       ++ "\n                   /                  \\    "))
       
ascii 4  = 
 putStrLn (("================================================== "
        ++ "\n|'.                     |                      .'|"
        ++ "\n|  '.                   |                    .'  |"
        ++ "\n|    '.                (O)                 .'    |"
        ++ "\n|      '. ______________________________ .'      |"
        ++ "\n|        :                              :        |"
        ++ "\n|        :                              :        |"
        ++ "\n|        :                              :        |"
        ++ "\n|        :                              :        |"
        ++ "\n|        :                __________    :        |"
        ++ "\n|      __:               /\\____;;___\\   :        |"
        ++ "\n|      ,':              | /         /   :        |"
        ++ "\n|    .'  :               . ---------.   :        |"
        ++ "\n|__.'    :               |\\         \\   :        |"
        ++ "\n|        :_______________| |---------|__:        |"
        ++ "\n|      .'                \\ |   (o)   |   '.      |"
        ++ "\n|    .'                   \\|_________|     '.    |"
        ++ "\n|  .'                                        '.  |"
        ++ "\n|.'                                            '.|"
        ++ "\n==================================================")) 
ascii 5 = putStrLn ("")
ascii 6 = 
 putStrLn (("              ^  ^  ^   ^        ^  ^   ^  ^  ^   ^  ^"
       ++ "\n             /|\\/|\\/|\\ /|\\      /|\\/|\\ /|\\/|\\/|\\ /|\\/|\\"
       ++ "\n             /|\\/|\\/|\\ /|\\      /|\\/|\\ /|\\/|\\/|\\ /|\\/|\\"
       ++ "\n             /|\\/|\\/|\\ /|\\      /|\\/|\\ /|\\/|\\/|\\ /|\\/|\\"
       ++ "\n                           /  \\             "     
       ++ "\n                          /    \\           "        
       ++ "\n                         /      \\        "       
       ++ "\n                        /        \\       "       
       ++ "\n                       /          \\         "      
       ++ "\n                      /            \\          "
       ++ "\n                     /              \\     "
       ++ "\n                    /                \\    "
       ++ "\n                   /                  \\    "))

ascii 7 = 
 putStrLn (("                             "
       ++ "\n                           _.-^-._    .--."
       ++ "\n                        .-'   _   '-. |__|"
       ++ "\n                       /     |_|     \\|  |"
       ++ "\n                      /               \\  |"
       ++ "\n                     /|     _____     |\\ |"
       ++ "\n                      |    |==|==|    |  |"
       ++ "\n  |---|---|---|---|---|    |--|--|    |  |"
       ++ "\n  |---|---|---|---|---|    |==|==|    |  |"
       ++ "\n ^jgs^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"))
ascii 8 = 
 putStrLn (("   *        *          __ *      ,    .     *         ." 
       ++ "\n                ,__   /     _ /' *        .          *"
       ++ "\n   .    *          \\\\/---./  \\\\    `/_          *   "  
       ++ "\n               *  .'\\\\, // './\\\\  //    *          "
       ++ "\n                 / --\\\\//    \\ \\\\//   ___       .    *  ."
       ++ "\n    *    .      :     \\#\\     :/ /  //--``        "
       ++ "\n                '  __/ \\ (_/  ( (  //       *       .   *"
       ++ "\n .            *  \\  _\\  \\ \\/ / \\ \\//  .   _  "
       ++ "\n      *           _( )_  ) )'_//\\  \\    _( )_ .   * "
       ++ "\n   _       .      |___|\\/#(.--'_/\"\\ \\  /|___|        .   * _ "
       ++ "\n _( )_            |_|_|\\ ,/        \\ \\//|_|_|            _( )_"
       ++ "\n |___|/\\/\\/\\/\\/\\/\\|___|/#(,%.-----.%\\  (|___|/\\/\\/\\/\\/\\/\\|___|"
       ++ "\n |_|_|\\/\\/\\/\\/\\/\\/|_|_|  /%%|R.I.P|%%\\  |_|_|\\/\\/\\/\\/\\/\\/|_|_|"
       ++ "\n |___|/\\/\\/\\/\\/\\/\\|___| /%%%|_____|%%%) |___|/\\/\\/\\/\\/\\/\\|___|"
       ++ "\n |_|_|\\/\\/\\/\\/\\/\\/|_|_|(  [_________] ~\"|_|_|\\/\\/\\/\\/\\/\\/|_|_|"
       ++ "\n |___|/\\/\\/\\/\\/\\/\\|___|~  ~~\"^\"^\"^\"~~   |___|/\\/\\/\\/\\/\\/\\|___|"
       ++ "\n |_|_|\\/\\/\\/\\/\\/\\/|_|_|     _-      _-  |_|_|\\/\\/\\/\\/\\/\\/|_|_|"
       ++ "\n |___|/\\/\\/\\/\\/\\/\\|___| _-      _-      |___|/\\/\\/\\/\\/\\/\\|___|"
       ++ "\n |_lc|\\/\\/\\/\\/\\/\\/|_|_|   _-         _- |_|_|\\/\\/\\/\\/\\/\\/|_|_|"
       ++ "\n[_____]~~\"^\"\"^\"~~[_____]         _-    [_____]~~\"^\"\"^\"~~[_____]"
       ++ "\n~~\"^\"~~          ~~\"^\"~~      _-       ~~\"^\"~~          ~~\"^\"~~  "))                     
ascii 9 = ascii 8
ascii 10 = ascii 8
ascii 11 = ascii 8
ascii 12 = 
 putStrLn ((" .. ........... .............  ........... . ..... ........ ......."
       ++ "\n ......  ....................%.... .... ..... .........%............"
       ++ "\n .@@@ ........ @@.... @@@@  . ............................  *  ....."
       ++ "\n ....@@ ..... @ .... @ .............   ....... .....; .... *** ....."
       ++ "\n .....\\@\\....@ .... @ ............................. #  .. *****  ..."
       ++ "\n  @@@.. @@@@@  @@@@@@___.. ....... ...%..... ...  {###}  *******"
       ++ "\n ....@-@..@ ..@......@@@\\...... %...... ....... <## ####>********"
       ++ "\n   @@@@\\...@ @ ........\\@@@@ ..... ...... ....... {###}***********"
       ++ "\n ....%..@  @@ /@@@@@ . ....... ...............<###########> *******"
       ++ "\n ...... .@-@@@@ ...V......     .... %.......... {#######}******* ***"
       ++ "\n ...... .  @@ .. ..v.. .. .     ............<###############>*******"
       ++ "\n ......... @@ .... ........    ,     .......   {## ######}***** ****"
       ++ "\n ..%..... @@ .. .%.... . .. .......   ... <###################> ****"
       ++ "\n . .... . @@ . .... .. .  .. `.... ......... {#############}********"
       ++ "\n .... ... @@ ... ..   .......... .. ....<################  #####>***"
       ++ "\n . .... ..@@@ ...... ...........  .........{##################}*****"
       ++ "\n ......... @@@  ....  ...........  .. <##########################>**"
       ++ "\n  @@@@ ....@@@  ... ............. ...... {###   ##############}*****"
       ++ "\n @@@@@@@  @@@@@ .. @ @@@@@@@@@@ QQ  <##############################>"
       ++ "\n @@@@@@@ @@@@@@@ @@@@@@@@@@@@@@@@@@@ ..... @@@@@@  @@@@@@@  @@@@"
       ++ "\n @@@@@@###@@@@@### @@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n @@@@@@@@###@##@@ @@@@@@@@@@@@@@@@@@@@@ @@@@@   @@@@@@@@@@@@@@@@@@@"
       ++ "\n @@@@@@@@@@@### @@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n -@@@@@@@@@#####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n http://ascii.co.uk/art/forest"))
ascii 13 = ascii 12
ascii 14 = ascii 12
ascii 15 = ascii 12
ascii 16 = ascii 12
ascii 17 = ascii 12
ascii 18 = ascii 12
ascii 19 = ascii 12
ascii 20 = ascii 12
ascii 21 = ascii 12
ascii 22 = ascii 12
ascii 23 = 
 putStrLn ((" .. ........... .............  ........... . ..... ........ ......."
       ++ "\n ......  ....................%.... .... ..... .........%............"
       ++ "\n .@@@ ........ @@.... @@@@  . .........................................."
       ++ "\n ....@@ ..... @ .... @ ..........................................."
       ++ "\n .....\\@\\....@ .... @ ..............................................."
       ++ "\n  @@@.. @@@@@  @@@@@@___.. ....... ...%................................"
       ++ "\n ....@-@..@ ..@......@@@\\...... %................................"
       ++ "\n   @@@@\\...@ @ ........\\@@@@ ..... ................................"
       ++ "\n ....%..@  @@ /@@@@@ . ....... ......................................"
       ++ "\n ...... .@-@@@@ ...V......     .... %............................"
       ++ "\n ...... .  @@ .. ..v.. .. .     ....................................."
       ++ "\n ......... @@ .... ........    ,    ............................ "
       ++ "\n ..%..... @@ .. .%.... . .. .......   ............................"
       ++ "\n . .... . @@ . .... .. .  .. `.... .................................."
       ++ "\n .... ... @@ ... ..   .......... .. ................................"
       ++ "\n . .... ..@@@ ...... ...........  .................................."
       ++ "\n ......... @@@  ....  ...........  .. ..............................."
       ++ "\n  @@@@ ....@@@  ... ............. ...... ..........................."
       ++ "\n @@@@@@@  @@@@@ .. @ @@@@@@@@@@ QQ  ................................"
       ++ "\n @@@@@@@ @@@@@@@ @@@@@@@@@@@@@@@@@@@ ..... @@@@@@  @@@@@@@  @@@@"
       ++ "\n @@@@@@###@@@@@### @@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n @@@@@@@@###@##@@ @@@@@@@@@@@@@@@@@@@@@ @@@@@   @@@@@@@@@@@@@@@@@@@"
       ++ "\n @@@@@@@@@@@### @@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n -@@@@@@@@@#####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
       ++ "\n http://ascii.co.uk/art/forest"))

ascii 24 = ascii 12
ascii 25 = ascii 12
ascii 26 = ascii 12
ascii 27 = 
 putStrLn (("            .        +          .      .          ."
       ++ "\n     .            _        .                    ."
       ++ "\n  ,              /;-._,-.____        ,-----.__"
       ++ "\n ((        .    (_:#::_.:::. `-._   /:, /-._, `._,"
       ++ "\n  `                 \\   _|`\"=:_::.`.);  \\ __/ /"
       ++ "\n                      ,    `./  \\:. `.   )==-'  ."
       ++ "\n    .      ., ,-=-.  ,\\, +#./`   \\:.  / /           ."
       ++ "\n.           \\/:/`-' , ,\\ '` ` `   ): , /_  -o"
       ++ "\n       .    /:+- - + +- : :- + + -:'  /(o-) \\)     ."
       ++ "\n  .      ,=':  \\    ` `/` ' , , ,:' `'--\".--\"---._/`7"
       ++ "\n   `.   (    \\: \\,-._` ` + '\\, ,\"   _,--._,---\":.__/"
       ++ "\n              \\:  `  X` _| _,\\/'   .-'"
       ++ "\n.               \":._:`\\____  /:\'  /      .           ."
       ++ "\n                    \\::.  :\\/:'  /              +"
       ++ "\n   .                 `.:.  /:'  }      ."
       ++ "\n           .           ):_(:;   \\           ."
       ++ "\n                      /:. _/ ,  |"
       ++ "\n                   . (|::.     ,`                  ."
       ++ "\n     .                |::.    {\\"
       ++ "\n                      |::.\\  \\ `.    .___."
       ++ "\n                      |:::(\\    |    !___!             "
       ++ "\n              O       |:::/{ }  |      |           (o"
       ++ "\n               )  ___/#\\::`/ (O \"==.___|_   O, (O  /`"
       ++ "\n          ~~~w/w~\"~~,\\` `:/,-(~`\"~~~~~~~~\"~o~\\~/~w|/~"
       ++ "\ndew   ~~~~~~~~~~~~~~~~~~~~~~~\\\\W~~~~~~~~~~~~\\|/~~"))
ascii 28 = putStrLn  (("                                 `                `                    "         
       ++ "\n                                `.-``      ```````-`          ``        "        
       ++ "\n              .-` +o`           `/s--.---:--:-::-:/.         `-o-:-     "        
       ++ "\n              `oo+/y+++++/:::::+od/.-.`--.-`-.---:s/....---:/+oydo`             "
       ++ "\n                -yNmdyso+++oo+:oo/.-.-:-/-:--:::-/++////+oydmNMMo               "
       ++ "\n                  -hMMNdmhhyyyyyyyyysdyyyyyyyhyyyhhddddmNMNMMMm:                "
       ++ "\n                    .od/so/:+sddhhhhhddhyyhhdhhyyyhhhysyyyyNNs`                 "
       ++ "\n                       .+s+++//o/+ooo+++++++++++o/+o//+/syoo`                   "
       ++ "\n                        :s/+o+/hyyyyyyyysyyhyhsyyyoy++//++.                     "
       ++ "\n                        shyysssssyhdhyddyhhdddhhso:yyosso+`                     "
       ++ "\n                        .sydhs-+ohMMNdMMMMMMMNNMho:ooddh/:`                     "
       ++ "\n                        .sdMMd:+oNMNmyMMMyNMNmNNh+:oyMMNo/                      "
       ++ "\n                        `sMMMNoohMNmd ██████ mNh/:sNNNNs:                      "
       ++ "\n                        `oMMMNdsdNmmd █▒▒▒▒█ NNdsoomNNmy:                      "
       ++ "\n                        `+MMMNdoddddh █▒▒▒▒█ mNds+ommNds:                      "
       ++ "\n                        `/MMNyo/hmdhy ██████ mNoo++hddhs/                      "
       ++ "\n                         /MMMdy/dNddhhMMNmdNNMNNsy/oyddhs:                      "
       ++ "\n                         :hddsy+mNmddhMMMMMMNMNmsy/ohssd+:                      "
       ++ "\n                         -shhys/NNNmdhMmdhhhmMNmso:+sssd+/                      "
       ++ "\n                         .oNdyh:dddhhsmo:---+ddho/:ssyhh+/                      "
       ++ "\n                         .os++/-hh/:---......----:/o++++:+.                     "
       ++ "\n                       `:-///////++++++osoo+ooooooosossssss`                    "
       ++ "\n                       .hsysosoososyyhhhdddhdhyyyhhhddmmNNN.                    "
       ++ "\n                       .mms oy:                       .dmNN`                    "
       ++ "\n                       `NNs sh:                       `dNNm`                    "
       ++ "\n                        NNo oN:                        NNNN`                    "
       ++ "\n                        NNo oN:                        mNmN`                    "
       ++ "\n                        mm+ oN:                        mNmN                     "
       ++ "\n                        dNo +N:                        dMmN                     "
       ++ "\n                        yN+ +M:                        hMmN                     "
       ++ "\n                        yN+ /M:                        sMmN                     "
       ++ "\n                        sN+ /M:                        oMmN                     "
       ++ "\n                        sN+ :M:                        +MNN             "
       ++ "\n                        oN+ :M:                        +Nmm             "
       ++ "\n                        oMo :d+                        ymNm             "
       ++ "\n                        +Mo                            -+Nm             "
       ++ "\n                        :Mo                              Nm             "
       ++ "\n                        :Mo                              Nm             "
       ++ "\n                        /md                             -Nd             "
       ++ "\n                        `/-                              +:          "))
ascii 29 = putStrLn  (("                _|_"
       ++ "\n                 |"
       ++ "\n             .-'''''-."
       ++ "\n          .-'    '-."
       ++ "\n       .-'  :::::_:::::  '-."
       ++ "\n   ___/ ==:...:::-:::...:== \\___"
       ++ "\n  /_____________________________\\"
       ++ "\n':'-._________________________.-'_"
       ++ "\n ':::\\ @-,`-[-][-^-][-]-`,-@ / _| |_"
       ++ "\n  '::| .-------------------. ||_ @ _|"
       ++ "\n   ::|=|*   ___  _  ___   *|=|'.| |"
       ++ "\n   ':| |'   ))_) )) ))_)  '| |::.^|"
       ++ "\n   _:|=|'  ((`\\ (( ((     '|=|::::::."
       ++ "\n _| || |'        _        '| |:::::::."
       ++ "\n|_   |=|'1634  _( )_  1789'|=|':::::."
       ++ "\n  | || |' (   (_ ~ _)   ) '| | ':::'"
       ++ "\n  |^||=|*  )    (_)    (  *|=| '::'"
       ++ "\n     | '-------------------' .::::'"
       ++ "\n     |_____________________.::::::'"
       ++ "\n   .'___________________.::::::''"
       ++ "\n   |_______________.::::'':::'''"
       ++ "\n .'_____________.::::::''::::''"
       ++ "\n            .:::'''' LGB .'::::'"
       ++ "\n         .:::::''':.   .:::::'"))
ascii 30 = putStrLn  (("         mNNNNNNNNNNNNNNNNNmNmmmNNNNNNNNNNNNNNNmmmmmmNNNNNNdmNNNmmmmmmNN"
       ++ "\n     mmmNNNNNNNNNNNNNNNNmNNmNmmNNNNNmmdhddhyhmy+//://+ydddmmddmNdmmNNmNNNNN"
       ++ "\n    mmmNNNNNNNNNNNNNNNNmmNmNmdmmhs+/                      :sdmmNNdddmmmNNNNNN"
       ++ "\n  mNmmNNNNNNNNNNNNmmNNmmmmmmh+/                             sdmmNmmdmNmNNNNNNN"
       ++ "\n NNNmNNNNNNNNNNNNdmNNmmmdh+:---                             -/ydmNmmmNmNmNNNNNNN"
       ++ "\nmNmmmNNNNNNNNNNmhhmNNmmd/-.                                   -/yddydmmNNmNNNNNN"
       ++ "\nmmmdmNNNNNNNNNdhhdNmdms:                                         /yyhmmNmmNNNNNN"
       ++ "\nmmNmmNNNNNNNNNdyddmms/-                                            sdddNNmmmmNNN"
       ++ "\ndmmmNNNNNNNNNmhhdhy+                                               oydddNNmmmNNN"
       ++ "\nmmmNNNNNNNNNNmdy+                                                   /shddNNmmdmN"
       ++ "\nNmNNNNNNNNNNNds                                                      /sdmNNmddmm"
       ++ "\nmNNNNNNNNNNNdy/                                                        ydmmmmmmN"
       ++ "\nNNNNNNNNNmmmh/                                                         shdmmmNNm"
       ++ "\nNNNNNNNNNNmy+                                                          omhhmmdNm"
       ++ "\nNNNNNNNNNmdo                                                          /ydydNmmdd"
       ++ "\nNNNNNNNNmmmmmhsoo+oyyyyoosssyhyo++os++ssmsooo+oshNNNNNNNNNNNNdddyo/+++yhhhNNNmdh"
       ++ "\nNNNNNNNmmmdmNddhhs+//ysdmmdmmmdo////+yhmmddddmmmmmNNNNNNNNNNNNNNNdo:/odmmmNNNNds"
       ++ "\nmmmmmmdmmmmmNmmmmdhssoosssso+++/://+dmyhhddmNNNNNNNNNNNNNNNNNNmhhysooosyhddddhdh"))
ascii 31 = ascii 3
ascii 32 = ascii 3
ascii 33 = putStrLn  (("                  _.._"
       ++ "\n   _________....-~    ~-.______"
       ++ "\n~~~                            ~~~~-----...___________..-----------__"
       ++ "\n                                           |   |     |"
       ++ "\n                                           | |   |  ||"
       ++ "\n                                           |  |  |   |"
       ++ "\n                                           |'. .' .`.|"
       ++ "\n___________________________________________|0oOO0oO0o|_______________"
       ++ "\n -          -         -       -      -    / '  '. ` ` \\    -    -"
       ++ "\n      --                  --       --   /    '  . `   ` \\    --"
       ++ "\n---            ---          ---       /  '                \\ ---"
       ++ "\n     ----               ----        /       ' ' .    ` `    \\  ----"
       ++ "\n-----         -----         ----- /   '   '        `      `   \\"
       ++ "\n     ------          ------     /          '    . `     `    `  \\  ---"
       ++ "\n            -------           /  '    '      '      `             \\"
       ++ "\n                    --------/     '     '   '                       \\"))
ascii 34 =putStrLn  (("                             ___....___"
       ++ "\n                     __..-:'':__:..:__:'':-..__"
       ++ "\n                 _.-:__:.-:'':  :  :  :'':-.:__:-._"
       ++ "\n               .':.-:  :  :  :  :  :  :  :  :  :._:'."
       ++ "\n            _ :.':  :  :  :  :  :  :  :  :  :  :  :'.: _"
       ++ "\n           [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]"
       ++ "\n           [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]"
       ++ "\n  :::::::::[ ]:__:__:__:__:__:__:__:__:__:__:__:__:__:[ ]:::::::::::"
       ++ "\n  !!!!!!!!![ ]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![ ]!!!!!!!!!!!"
       ++ "\n  ^^^^^^^^^[ ]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[ ]^^^^^^^^^^^"
       ++ "\n           [ ]                                        [ ]"
       ++ "\n           [ ]                                        [ ]"
       ++ "\n     jgs   [ ]                                        [ ]"
       ++ "\n   ~~^_~^~/   \\~^-~^~ _~^-~_^~-^~_^~~-^~_~^~-~_~-^~_^/   \\~^ ~~_ ^"))
ascii 35 = putStrLn  (("                                       ,.=,,==. ,,_"
       ++ "\n                      _ ,====, _    |I|`` ||  `|I `|"
       ++ "\n                     |`I|    || `==,|``   ^^   ``  |"
       ++ "\n                     | ``    ^^    ||_,===TT`==,,_ |"
       ++ "\n                     |,==Y``Y==,,__| \\L=_-`'   +J/`"
       ++ "\n                      \\|=_  ' -=#J/..-|=_-     =|"
       ++ "\n                       |=_   -;-='`. .|=_-     =|----T--,"
       ++ "\n                       |=/\\  -|=_-. . |=_-/^\\  =||-|-|::|____"
       ++ "\n                       |=||  -|=_-. . |=_-| |  =|-|-||::\\____"
       ++ "\n                       |=LJ  -|=_-. . |=_-|_| =||-|-|:::::::"
       ++ "\n                       |=_   -|=_-_.  |=_-     =|-|-||:::::::"
       ++ "\n                       |=_   -|=//^\\. |=_-     =||-|-|:::::::"
       ++ "\n                   ,   |/&_,_-|=||  | |=_-     =|-|-||:::::::"
       ++ "\n                ,--``8%,/    ',%||  | |=_-     =||-|-|%::::::"
       ++ "\n            ,---`_,888`  ,.'''''`-.,|,|/!,--,.&\\|&\\-,|&#:::::"
       ++ "\n           |;:;K`__,...;=\\_____,=``           %%%&     %#,---"
       ++ "\n           |;::::::::::::|       `'.________+-------\\   ``"
       ++ "\n          /8M%;:::;;:::::|                  |        `-------"))
ascii 36 = putStrLn  (("MMMMM:  /mMMMMMMMdMMMMMMhM/My `M+Md/.Mm:mmMMMMMNmy-Mo/.Mh-M`  dmmMMMMMMMd-`:MMMM"
       ++ "\nMMMMMo-hMMMMMMMN: /-  `/mM:My `M+Md:-Mm:mmMMNMMNmy-Mo-.Mh-M`  s/ /mMMMMMMN+yMMMM"
       ++ "\nMMMMMMMMMMMMMy+o.    /NMMM:My `M+Md`.Mm:mmMmdmNNmy-Ms.-Mh-M`  o-  /MMMMMMMMMMMMM"
       ++ "\nMMMMMMMMMMMd-       /MMMMM-My `M+Md:.Mm:Nmmy.+mNms-Ms/.My-M`  my  :MhsMMMMMMMMMM"
       ++ "\nMMMMMMMMMMs`        NMMMMM-My `M/Md.-Mm:Nmh`  +mms-My.+My:M`  mh  :Mh /NMMMMMMMM"
       ++ "\nMMMMMMMMNMn     `  `MMMMMM.Mh `M/Md  mm:Nm.   `dms-MdydMy:M   mh  :Mh +MMMMMMMMM"
       ++ "\nMMMMMMMMMMn        `MMMMMM`Mh `M/mM  Md:my     +ms.MMhMMo:M   so  -Mh+Mh/NMMMMMM"
       ++ "\nMMMMMMMMMMn        `MmMMMM`o+ `M:mM  +`-m+     -ms :hMN/`:M   ::  -MmNo  oMMMMMM"
       ++ "\nMMMMMMMMMMMn       `M+MMMM`-- `M:mM    -m+     -ms  `+-  :M   .-  -MMd  oMMMMMMM"
       ++ "\nMMMMMMMMMMMn    `  `ddMMMM--.-:MdmM++++hmo     -md+++oooodM-..``  .MMs .MMMMMMMM"
       ++ "\nMMMMMMMMMMMn` .osoodMsNMMMNNNMMNmmNNNNNNmo     -mmNNNNmNNNNMNmmdhyyMMo :MMMMMMMM"
       ++ "\nMMMMMmhdhooys+yMMNmdhmmmNNNMMMMNNNMNNNNNNo__sMs_mNNNNMNMNNNMMMMMMMMMMo :MMMMMMMM"
       ++ "\nMMMM:+yddhshMss                            sMMMs          +ydNMMMMMMMo :MMMMMMMM"
       ++ "\nMMMd--..:dmNd                             sMMMMMs              ohmMMMh/oMMMMMMMM"
       ++ "\nMMMNN  ` yMM:                            sMMMMMMMs               `-+NMMNmmdhhMMM"
       ++ "\nMMMMM    yMM:                            sMMMMMMMMs                   hhyyssyMMM"
       ++ "\nMMMMM    sMM:                            sMMMMMMMMs                      MMMMMMM"
       ++ "\nMMMMM    sMMo                           sMMNNNNMMMMs                         mMM"
       ++ "\nMMMMM    NMMN                          sMMMMMMMMMMMMs                        hMM"
       ++ "\nMMMNm   NMMMMN                         sMMMMMMMMMMMMs                        hMM"
       ++ "\nMMMMM  NMMMMMMN                       sMMMMMMMMMMMMMMs                     ./mMM"
       ++ "\nMMMMm  oshdNMMy                      sMMMMMMMMMMMMMMMMNs                   -/mMM"))
ascii 37 = putStrLn  (("                                     -  s/  `:``                                "
       ++ "\n                               .yoh: d  MM..y:dm`   ..                          "
       ++ "\n                           s-  +.-MN`M  NMoo. yM: `y/mh`                        "
       ++ "\n                           MN` s  NM.M  mMhy  yM/ /: hM-                        "
       ++ "\n                           mM/ s  hM-N  dMmh  yM/ s  dM-                        "
       ++ "\n                        /  sMs s` sM/m  dMNy  hM: y  NM`                        "
       ++ "\n                     d+ -+ :Mm s. +Msd  hMMy  dM-.o `Mm :                       "
       ++ "\n                     sM/`s `MM`o- /MNd  dMMh  mM.+: :My y  Mh                   "
       ++ "\n                     .Mm y  dM-+: -MMd  dMMy  NM`y` +Mo:  /Ms                   "
       ++ "\n                   y  dM:y  sM+// .MMh  dMMo  MN h  yM:y  sM/                   "
       ++ "\n               `   s` +Ms+- /My:o  MMh  dMM+ `Mm`y  mM`h  dM. ...`              "
       ++ "\n                 +`/  .Mm:/ .Md-s  NMy  mMM: .Mh-o `Mm-o `Mm s  No              "
       ++ "\n              y  Ms`s  mM-o  mM.h  dMy  mMM. :Ms+: :Myo- /Ms/h -Ms              "
       ++ "\n              y` hM+y  sM+s  hM:d  yMy  NMM` +M+h. +M+h  yM/h. yM:              "
       ++ "\n              :o .NNy. :Mhs  oMoh  sMy  MMN  oM/m  yM/y  NNo/ -Md               "
       ++ "\n             ` y` sMM+  NMh  :Mdh  +My `MMN  hM+h  mMh/ -MNh  hM-  +:           "
       ++ "\n          :s  y:+ `NMd  hMd. .MMN``:Md.+MMN` mMys `MNM` oMM- -Mh+  mM           "
       ++ "\n          .o .Ndh` +MM` +MNs  MMM/hmMMmNMMMhsMMM+ -Mdh  dMs  dMo  :My           "
       ++ "\n           y. +MNs `mM/ .MMm:/MMMMdNMN./MMNssMMMdohNMo .MN` /MM. `mN.           "
       ++ "\n           .y  hMN. /My  NMmMmMMmd-sMMdhMMNhmMMMMmNNM- +Mo  mMh  sM+            "
       ++ "\n            /+ `mMy  dN` hM`o/dM--NmMN sMMMo.MMMN yMN  dm` +MN. :My             "
       ++ "\n             s- :MM- :M+ oN /dMM` NMMd +MMM: NMMh oMd :M/ `NM/ `Nm`    .        "
       ++ "\n           s. y  oMh  hNsmd :ddM  mMMh /MMM- NMMy +MNyNd  sMs  hM:.  .Nd        "
       ++ "\n        o` Mo.o  hM: .Moyh :MMM  dMMh /MMM. mMMs +M..m: .Mm` oMs:o  hN.        "
       ++ "\n        `s` /Ny/. .Nd  sy-h -MMN  hMMy /MMM. mMMs +M+hh  hN- :MN//  dm-         "
       ++ "\n         `s. -md/  :M/ .Nmh :MMN  hMMy /MMM. mMMs +MsN. :M+ .NMy` .md.          "
       ++ "\n           o: `hMs  sm` yMh :MMM  hMMy /MMM. NMMs +Mm+-:mh `mMh` :Nh`           "
       ++ "\n            ++ `sM+  dmdNMh :MMM  hMMy /MMM. NMMs +MMmhMm``dMs` +No             "
       ++ "\n             ms  oN- .Ny.md /MMM  hMMy +MMM- NMMy oMM.oM:-dMs `sN/              "
       ++ "\n            :yoh` +m. /Nohd /MMM` hMMh +MMM- NMMy oMMsNs.mom .hN:               "
       ++ "\n       -/.` y/:mo:/hd/:NMMN +MMM. hMMh oMMM/ MMMd sMmMM/oh.m+NM/+:----.         "
       ++ "\n       y.smmM:.MMMs.mMNMMMM +MMM- dMMd sMMM+`MMMm yM-oMNMs MMMs yMNNNNy         "
       ++ "\n       ms`hMM-`MMy oMMMMMMM-sMMM/ NMMN yMMMy-MMMM`hMh`oMMo NMd`-NMMMMMh         "
       ++ "\n       NM:`mM- MN`:NMMMMMMMymMMMh:MMMMomMMMNsMMMMsNMMo hM+ NN-`mMMMMMMh         "
       ++ "\n       NMm.-M- N+.mMMMMMMMMmNMMMNdMMMMmmMMMNmMMMMdNMMM:`mo`M/`hMMMMMMMh         "
       ++ "\n       MMMh`d- m-dMMMMMMMMM/dMMMm-NMMM/sMMMh+MMMM/yMMMN.-y+y sMMMMMMMMh         "
       ++ "\n       MMMMsd: dmMMMMMMMMMMdMMMMMmMMMMNMMMMMmMMMMmMMMMMd`/N.oMMMMMMMMMh         "
       ++ "\n       MMMMMM: hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy odMMMMMMMMMMh         "
       ++ "\n       MMMMMM/ yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+`hMMMMMMMMMMh         "
       ++ "\n       MMMMNh+ yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/s:`mMMMMMMMMMh        " 
       ++ "\n       MMMM/ys yoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo hd.-NMMMMMMMMh       "  
       ++ "\n       MMMN`mh.d:+MMMMMMMMy////////////////////////dMMM:od-y.yMMMMMMMMh      "   
       ++ "\n       MMNmdMMmMMddMMMMMMM/                        hMNmNMMNMNNNMMMMMMMh     "    
       ++ "\n       MMsoMMd`NMhsMMMMMNs`                        hMdyMMM-NMhoMMMMMNh/    "     
       ++ "\n       MMNMMMMhMMMNMNmy/`                          hMMMMMMyMMMMMNNh+.   "))        
            
ascii 38 = putStrLn(("                   `-..y/+s .-`                   "
       ++ "\n                   y+oom:+moo+y                   "
       ++ "\n               -+////+s/+y/s+////+-               "
       ++ "\n              ++     `+/../+`     ++              "
       ++ "\n             `y.  -++- `  ` -++-  .y`             "
       ++ "\n             .h::+-`+s-    -s+`-+::h.             "
       ++ "\n              s//s   s-    -s   s//s              "
       ++ "\n             `yos:  .o      o.  :soy`             "
       ++ "\n          `/+sddyssshyssssssyhsssydds+/`          "
       ++ "\n          so/ohhyos++hsyooysh++soyhho/os          "
       ++ "\n         .dss  -shsshs.:ss:.shsshs-` ssd.         "
       ++ "\n          sss `  `dh+++/++/+++hd` -: sss          "
       ++ "\n          `++-:   om  ``````  mo  /- ++`          "
       ++ "\n          -- ``  hdyooooooooooydh ` .`::          "
       ++ "\n          /+ -  `M/````````````/M`  /`//          "
       ++ "\n   `:/+ooosh/o+++ms++////////++sm++++/ysooo+/:`   "
       ++ "\n  -o/.dy++++++/////+++ooooo+////////++++++yd./o-  "
       ++ "\n .ys::+yy//sooso/.-:+ssooooss:.../osoos//yy+::sy. "
       ++ "\n sso::y/.ym/ ``-/+-/o+---..-os-.+/-`` /my./y::oss "
       ++ "\n yo///so `sh/--.-/yho-.-:.`./shs/-.--/hs` os///oy "
       ++ "\n :s.o++o   .::/++ymhhosyoossshhmy++/::.   o++o.s: "
       ++ "\n    +o`/         od++ :+-`/:-+/do         /`o+    "
       ++ "\n     .`s.        yy+o./o-.+/-+/yy        .s`.     "
       ++ "\n      -/+ `..-:/+myos/oo::o+:++ym+/:-..` +/-      "
       ++ "\n     `//ysyyysssoMo//++++/+++//oMosssyyysy//`     "
       ++ "\n  .+yhyooo/--::-.M+/::::--::::/+M.-::--/oooyhy+.  "
       ++ "\n.yyoys+:-:...-.`:M.``........``.M:`.-...:-:+syoyy."
       ++ "\nmo   `.-:://///+oy++++++++++++++yo+/////::-.`   om"
       ++ "\noh:``                                        ``:ho"
       ++ "\n -shy+/+/:-......````````````````......-:/+/+yhs- "
       ++ "\n   .hs.o+oyo/::sooss/:os++s/:/ssoos::/oyo+o.sh.   "
       ++ "\n     /hh+`.:o:+/.`.:++s. `:o/+:.`./+:o:.`+hh/     "
       ++ "\n       :sys+oyho.```-/o/``+s/-```.ohyo+sys:       "
       ++ "\n          `-:/+hNssssssssssssssssNh+/:-`          "
       ++ "\n             :shyo/o/+o////o+/o/oyhs:             "
       ++ "\n           .hy+:.--`.:`    `:.`--.:+yh.           "
       ++ "\n           yy/. /` ./        /. `/ ./yy           "
       ++ "\n           odo  +  /.        ./  +  odo           "
       ++ "\n            sms /. `+        +` ./ sms            "
       ++ "\n            /ms++s++yo++++++oy++s++sm/            "
       ++ "\n           /N.                      .N/           "
       ++ "\n           `oyyyyyyyyyyyyyyyyyyyyyyyyo`           "))
ascii 39 = ascii 3
ascii 40 = ascii 3
ascii 41 = putStrLn ((""
       ++ "\n :----------------------------------.......................``..````..````.```````"
       ++ "\n --------------------.....................................`````    ``````````````"
       ++ "\n -----------------.......................````````````````````````````````````````"
       ++ "\n -------------..............``````./o/..::--.````````````````````````````````````"
       ++ "\n ------.....................`````:+++os/.:/:::-.````````````````                 "
       ++ "\n ......................```````::/oo++os+/-::/::oo-````````` `                  ` "
       ++ "\n ....................```````./s++o+++yy++::-:+++/oo-````                         "
       ++ "\n .......................-:/+++++++//++ooo::::/:/++o+/-.`                         "
       ++ "\n ............--:/::/+ossss+++o+++++oyyo+osoyyyo+ooyos+o/-.`                ``..` "
       ++ "\n ..........:sydhdssssosssoo++++++++yyhyho+osoosyhyyyyhhyss+/-`````````.-///++oo++"
       ++ "\n :/++++o+oymNNdyssyyhsyhsoo+soo+++oooooyhyo+++:/oyhdydmmdddhyys+-`..-/ooooyhhsyhh"
       ++ "\n ssyhhyhdmmNNdhhhhdmmhyoossssosssoyyysyyysyhyyysssyyhdmdddhhssyhhhhhsooossssoshmm"
       ++ "\n hdmmmNNNmNmhdmmmmmdmmdyhyyhdmdydddddhdddhhddddhmmmmmNNNMNmmddhyhmmmmddyyyyyyhmmd"
       ++ "\n mmdNMNNNNmmNNNNNNNmmmmddhddNNMMNmmmmdddddddddmmNMNNMMMMMMMNNNmdddmmNNNNmmmmmMNNN"
       ++ "\n NNMMNNNNNNMMNNNNmmNmmmmNNNNNMMMMMMNmmmmNNNNmmNNNMMMMMMMMMMMMMMMNNNNMNNMMMMMMMMMM"
       ++ "\n MMMMNNMMMMMMMMMMMMNNNNNNNNMMMMMMMMNNNNNNNNNNMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
       ++ "\n MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
       ++ "\n MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
       ++ "\n MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
       ++ "\n MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
       ++ "\n MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"))
ascii 42 = putStrLn (("                         ____________________________                      "
       ++ "\n                       ,'____________________________'.                   "
       ++ "\n                       |ddhdhdhdhdhdhdddhdhdhhdhdhddddd|                  "
       ++ "\n                      ,|odhdhdhdhdhdhdhdhdhdhdhdhdhdhdo|,                 "
       ++ "\n                    ,'___________________________________',               "       
       ++ "\n                    |hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh+|               "       
       ++ "\n                    |hddddhhhhddddhhddhhdddhhhhhhhhhhhhhho|               "      
       ++ "\n                 ,-'|ooo////+o+++oo++++/+++++/++++/////+++|:_..           "       
       ++ "\n               .'______________________________________________'-.        "        
       ++ "\n               |yyyyyysss/:/+oo++o++++//+++/+++++o++ooosyyyyhhhh.|        "       
       ++ "\n               |hhhhhhhhhhhhhhhhhhhhhhhyyyyssssyysysyssyhhhhhhhd-|        "       
       ++ "\n               |ddhhhhhhhddddddhhhhhhhhhhhhhhhhhhhhhyhhhhhhhhhhd.|        "       
       ++ "\n            _.-|sooooooooooo++++ooooo+++++++++++++/////+++++++++/|-._     "    
       ++ "\n         .-'                                                         '-.. "       
       ++ "\n         |yhhhhhhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhhhhdddddddd:|"       
       ++ "\n         |dddhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhddh|"       
       ++ "\n         |ddddddhhhhhhhhhdddddhhhhhhhhhhhhhhhhhhhhddddddddddhhhhhhhhhhhhd|"       
       ++ "\n         |odddddddddddddddddddddhhhhhhhhhhhhhhhdddddddddddddhhhhhhhhhhhhd|"       
       ++ "\n         ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾"))     
ascii 43 = ascii 42
ascii 44 = putStrLn  (("               (  .      )                    " 
       ++ "\n           )           (              )       "
       ++ "\n                 .  '   .   '  .  '  .        "
       ++ "\n        (    , )       (.   )  (   ',    )    "
       ++ "\n         .' ) ( . )    ,  ( ,     )   ( .     "
       ++ "\n      ). , ( .   (  ) ( , ')  .' (  ,    )    "
       ++ "\n     (_,) . ), ) _) _,')  (, ) '. )  ,. (' )  "
       ++ "\n   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"))
ascii 45 = putStrLn  (("                                            )           "      
       ++ "\n                                  ( /(   (  (          "
       ++ "\n                                )\\()) ))\\ )(   (     "
       ++ "\n                              ((_)\\ /((_|()\\  )\\ )  "
       ++ "\n                              | |(_|_))( ((_)_(_/( "
       ++ "\n                              ...--..--.----.----.` "                            
       ++ "\n                               shhyhhhhhhhhhhhhhho   "                           
       ++ "\n                                +yyyyyyyyyyyyyyy+     "                          
       ++ "\n                                `hmmmmmmmmmmmmdh`      "                         
       ++ "\n                                 `h-o-h.o`h-o-h`        "                        
       ++ "\n                                  .-s/-:s:-/s-.          "                       
       ++ "\n                                 /hhhhhdhdhhhhh:          "                      
       ++ "\n                                  ::`:/-o-/-`::            "                     
       ++ "\n                                  y:./d-M-m:.:s            "                     
       ++ "\n                                  s:-:d:M-m:-:y              "
       ++ "\n                                  s/-/d:M-d:-:y              "                   
       ++ "\n                                  s/-/d:M-m:-/y              "                                                 
       ++ "\n                                 .ss//h:M-d:+sy.             "                   
       ++ "\n                                 .ys+/d:M-d:+sy.             "                   
       ++ "\n                                 .:+--+.y.o.:/:.             "                   
       ++ "\n                                 /+h//h-M-d/+h+:             "                   
       ++ "\n                                 //d/+h-M:h+/d+/             "                   
       ++ "\n                                 +:m/oh-M-ho/m/+              "
       ++ "\n                                 o:N:sh-M-ho:N:o              "                  
       ++ "\n                                 y-N-sh:M:ys:N-s              "                  
       ++ "\n                                 y-M-hy:M-hy:M.y              "                  
       ++ "\n                                 d.M-hy:M-hy-M.h              "                  
       ++ "\n                                 s y.dy.-.yd-y s              "                  
       ++ "\n                                  y` d+.d.+h `y               "                  
       ++ "\n                                 :Ms   mMm   sM:              "                  
       ++ "\n                                 mMM  /MMM:  NMm              "                  
       ++ "\n                                `NsN. dNoNh -NsN`             "                  
       ++ "\n                                 N N  sh do `m N              "                  
       ++ "\n                                `o`+. ++ ++ .o`o`            "
       ++ "\n                                dNNNNNNNNNNNNNNNh            "
       ++ "\n                              `::/://:/:/:/:///:::           "
       ++ "\n                              :syyyyyyyyyyyyyyyyys-          "
       ++ "\n                            `ddddddddddddddddddddddd         "
       ++ "\n                            `ddddddddddddddddddddddd`        "
       ++ "\n                           `//://///////////////:////`  "))
ascii 46 = ascii 3
ascii 47 = putStrLn  ((",_____________________________,"
       ++ "\n|                             |"
       ++ "\n|                    _        |"
       ++ "\n|                   | |       |"
       ++ "\n|      ___ _ __   __| |       |"
       ++ "\n|     / _ \\ '_ \\ / _` |       |"
       ++ "\n|    |  __/ | | | (_| |       |"
       ++ "\n|     \\___|_| |_|\\__,_|       |"
       ++ "\n|                             |"
       ++ "\n|    _________________        |"
       ++ "\n|    |               |        |"
       ++ "\n|    |_____.   ._____|        |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |   |              |"
       ++ "\n|          |___|              |"
       ++ "\n|                             |"
       ++ "\n|_____________________________|"))
ascii 48 = ascii 47
ascii 49 = putStrLn  (("hsysyhoooo/o/osohys/````                               .hddhhhmdmNmmmdmmmydddmNd"
       ++ "\nhyshdhyy++oho+++yhys/-                                 :dddyhdmdddmmNNNNddmdmmdd"
       ++ "\ndyyydhss+oohyys/oshsos-                                ohddhhhyhhmmmmNmdhddddddm"
       ++ "\ndhyhdsssooooyoos+shyo+o`                              `yhhdhyyddhdmmNNdhhmdhmhmm"
       ++ "\nmhydssyhoso+ydosoosysys/                              -hyhdhhyhhdmmmmNhdNmddhmmd"
       ++ "\nmhysyhyys/s+oyoso++ooss+                              +hhdhdmydhdmmNNmhmmddmNNmh"
       ++ "\nmmhsyyyyhy+:oohsss+/yo+y:                            .yyhdddhhdhdmNNNmhdmNdmmmhh"
       ++ "\nmmdhy+ooso/ooohss+//yo+ss:/.                         syhdhdmdhdmdhdmNmhydmmdmdhh"
       ++ "\nmmddhyooooohsos:+h:/oss+ssss`                       .yhyyhddddmhhddmmNdydddNdhmm"
       ++ "\nNmNdddhhdmhdmdhyos+//y+o+sos:                       /hhhydddymmydmNNNNdhmhddhdmN"
       ++ "\nNNNdhhmmdhdmddhhdhhy:ooo++/+o                     `:shyhhdmhdmdhdmNNNmdmmmmhddhd"
       ++ "\nNNNmmdhmmhdmdhdhdddds+o+os++/-                   .ysydhhhddhhmdhmNNNNNmmNmmNdhdd"
       ++ "\nNNNmmmddddmmdhddmmddhoyoss++//-                 .+ssyyydhdddddmmmNNNNNNNNmdmhddd"
       ++ "\nmmNmmNmmmmmmmmmmmmmddhhys/+/o++:              `+oyysyhhdddmhddddNNNNNMmmdydddddd"
       ++ "\nmNmmddmmmNmNmmmmmmmhmddmmd+++oso-            `+oshhyyhhhdddhdddmNmNMNNNdhhhddmmd"
       ++ "\nmNmmmddmmNNNdmmmdmmdmmhdhhyo//oso.        ``.oooshsyhhhddmmmmmmmNNNNMmmdhhmmNmmd"
       ++ "\nNNmNNNddNNNNmmmmmdddmddhhddh+++ys+:...`` :ssooooyhyhhhhhdddmmdmNNNNNNdhhhhddmmmd"
       ++ "\nNNmNNNNmNNNNdmmNmmmdNmmddhddsoooo+++://++osooooshdhhhhhhhhddddmNNNNNNhhhhddNNmdd"
       ++ "\nNNNNNNNNNNNNmmmNNmmmNNNmmmdmddho+os+o+/+osssoooyddyhhddhyhmmmmNmNNmmhhdhmmdmNmmd"
       ++ "\nNNNNmNNNNNNNNmmmmmmmNNNNmddmmddmhhssoooosooos+shdhhhhhhdmmNmmNNmmmmmmmdddmmmmddm"
       ++ "\nNNNNNNNNNNNNNmNmmmmmmNNmmmmmmdmmmdddsossoosssyyhdyhhhhhddmmmNNNNNNNNNNmmNmdddmmN"
       ++ "\nNNNNNNNNNNNNNNNNNNNNmmmmmmmmNNmmmddmyossooossshhhhhdhhdddmmmmNNNNNNNNNNNNNNNNNNN"
       ++ "\nMMMNNNNNNNNNNNNNNNmmmmNNNNmdmmmNmmmmdyhhssyyyydddddmdhdddmdddmNNNNNNNNNNNNNNNNNN"
       ++ "\nMMMMNNNNNNNNNNNNNNNNNNNmNNmmmmmmmNNNNmmmmmNNmhddhhhhdddNNNmNNNNNNNNNNNmNNNNNNMNN"))
ascii 50 = putStrLn ("")
ascii 51 = putStrLn ("")
ascii 52 = putStrLn ("")

ascii 53 = do
    setSGR [SetColor Foreground Vivid Red]
    putStrLn (("               ▄▄▄█████▓ ██░ ██ ▓█████             "
          ++ "\n               ▓  ██▒ ▓▒▓██░ ██▒▓█   ▀             "
          ++ "\n               ▒ ▓██░ ▒░▒██▀▀██░▒███               "
          ++ "\n               ░ ▓██▓ ░ ░▓█ ░██ ▒▓█  ▄             "
          ++ "\n                 ▒██▒ ░ ░▓█▒░██▓░▒████▒            "
          ++ "\n                 ▒ ░░    ▒ ░░▒░▒░░ ▒░ ░            "
          ++ "\n                   ░     ▒ ░▒░ ░ ░ ░  ░            "
          ++ "\n                 ░       ░  ░░ ░   ░               "
          ++ "\n                         ░  ░  ░   ░  ░            "
          ++ "\n                                                   " 
          ++ "\n                             █████▒▒█████    ▄████ "
          ++ "\n                           ▓██   ▒▒██▒  ██▒ ██▒ ▀█▒"
          ++ "\n                           ▒████ ░▒██░  ██▒▒██░▄▄▄░"
          ++ "\n                           ░▓█▒  ░▒██   ██░░▓█  ██▓"
          ++ "\n                           ░▒█░   ░ ████▓▒░░▒▓███▀▒"
          ++ "\n                            ▒ ░   ░ ▒░▒░▒░  ░▒   ▒ "
          ++ "\n                            ░       ░ ▒ ▒░   ░   ░ "
          ++ "\n                            ░ ░   ░ ░ ░ ▒  ░ ░   ░ "
          ++ "\n                                      ░ ░        ░ "
          ++ "\n                                                   "))
    setSGR [Reset]
ascii 54 = putStrLn  (("                              __"
       ++ "\n                            .d$$b"
       ++ "\n                          .' TO$;\\"
       ++ "\n                         /  : TP._;"
       ++ "\n                        / _.;  :Tb|"
       ++ "\n                       /   /   ;j$j"
       ++ "\n                   _.-\"       d$$$$"
       ++ "\n                 .' ..       d$$$$;"
       ++ "\n                /  /P'      d$$$$P. |\\"
       ++ "\n               /   \"      .d$$$P' |\\^\"l"
       ++ "\n             .'           `T$P^\"\"\"\"\"  :"
       ++ "\n         ._.'      _.'                ;"
       ++ "\n      `-.-\".-'-' ._.       _.-\"    .-\""
       ++ "\n    `.-\" _____  ._              .-\""
       ++ "\n   -(.g$$$$$$$b.              .'"
       ++ "\n     \"\"^^T$$$P^)            .(:"
       ++ "\n       _/  -\"  /.'         /:/;"
       ++ "\n    ._.'-'`-'  \")/         /;/;"
       ++ "\n `-.-\"..--\"\"   \" /         /  ;"
       ++ "\n.-\" ..--\"\"        -'          :"
       ++ "\n..--\"\"--.-\"         (\\      .-(\\"
       ++ "\n  ..--\"\"              `-\\(\\/;`"
       ++ "\n    _.                      :"
       ++ "\n                            ;`-"
       ++ "\n                           :\\"
       ++ "\n                           ;  "))
   
   
