module Ascii where

import System.Console.ANSI

ascii :: Int -> IO ()
ascii 0 = putStrLn ("                     ▄▄▄█████▓ ██░ ██ ▓█████\n               ▓  ██▒ ▓▒▓██░ ██▒▓█   ▀\n               ▒ ▓██░ ▒░▒██▀▀██░▒███\n               ░ ▓██▓ ░ ░▓█ ░██ ▒▓█  ▄\n                 ▒██▒ ░ ░▓█▒░██▓░▒████▒\n                 ▒ ░░    ▒ ░░▒░▒░░ ▒░ ░\n                   ░     ▒ ░▒░ ░ ░ ░  ░\n                 ░       ░  ░░ ░   ░\n                         ░  ░  ░   ░  ░\n\n                             █████▒▒█████    ▄████\n                           ▓██   ▒▒██▒  ██▒ ██▒ ▀█▒\n                           ▒████ ░▒██░  ██▒▒██░▄▄▄░\n                           ░▓█▒  ░▒██   ██░░▓█  ██▓\n                           ░▒█░   ░ ████▓▒░░▒▓███▀▒\n                            ▒ ░   ░ ▒░▒░▒░  ░▒   ▒\n                            ░       ░ ▒ ▒░   ░   ░\n                            ░ ░   ░ ░ ░ ▒  ░ ░   ░\n                                      ░ ░        ░\n")
ascii 1 = putStrLn ("\\n ____________________________________________________________________\n|    The map shows you the most important places in the country.   |\n|                                                                  |\n| The forests in the north, formerly called the forest of Elwyn.   |\n|      In the east, the Great Castle Minas..something.             |\n|               A Grand Canyon in the south.                       |\n|   In the west is a big mountain, it's called Mountain Doom.      |\n|                                                                  |\n'------------------------------------------------------------------'\n")
ascii 54 = putStrLn ("     .---.\\n    |  _  |\\n    | (o o)|\\n   .\\   /    \\n    \\_/|\\n |   \\n   |____|\\n\\n            .  .\\n         .  |  .\\n      .  |  |  .\\n     |   |  |   |\\n     |   |  |   |\\n      \\  |  /\\n        \\|/\\n         |\\n")
ascii i = putStrLn ("")
