cabal-version:      2.4
name:               thefog
version:            1.0.0
synopsis:           The Fog Text Adventure Game
license:            BSD-3-Clause
author:             Xethrocc
maintainer:         xethrocc@gmail.com
category:           Game
build-type:         Simple

executable thefog
    main-is:          main.hs
    other-modules:    Ascii,
                      GameActions,
                      GameConstants,
                      GameData,
                      GameTypes,
                      GameUtils
    build-depends:    base ^>=4.18,
                      array,
                      mtl,
                      random,
                      ansi-terminal,
                      containers
    hs-source-dirs:   .
    default-language: Haskell2010
